name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

# Minimal permissions for the whole workflow (deploy job will add pages/id-token)
permissions:
  contents: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you have a build step, uncomment and adjust:
      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - name: Install & build
      #   run: |
      #     npm ci
      #     npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # If you built to ./build or ./dist, change this to that folder.
          path: .

  deploy:
    needs: build-and-upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

