name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you have a build step (npm/yarn), run it here and upload the build output instead of '.'
      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      # - name: Install & build
      #   run: |
      #     npm ci
      #     npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # If you built to ./build or ./dist, change this to that path.
          path: '.'

  deploy:
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
